# Generated by Django 4.2 on 2023-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="selectors",
            field=models.JSONField(default=list),
        ),
    ]
