version: '3.9'

services:
  web:
    build: .
    command: uwsgi --http=0.0.0.0:80 --module=what_re.wsgi
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - djangonetwork
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - djangonetwork

volumes:
  postgres_data:


networks:
  djangonetwork:
    driver: bridge
