version: '3.9'

services:
  web:
    build: .
    command: uwsgi --http=0.0.0.0:80 --module=what_re.wsgi
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - database_default
    links:
      - "database_default"

  database_default:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_MANAGER: "fsm-postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
